// src/config/site.ts
// Site configuration generated by customization wizard
// Feel free to modify these settings as needed

export const SITE_CONFIG = {
  // Basic site information
  name: "Fake Company",
  tagline: "",
  description: "This is a demonstration website.",
  url: "https://fakecompany.abc",
  domain: "fakecompany.abc",

  // Contact information
  contact: {
    email: "bob@fakecompany.abc",
    phone: "+1 (555) 123-4567",
    address: {
      street: "123 Main Street",
      city: "Your City",
      state: "ST",
      zip: "12345",
      country: "United States",
    },
  },

  // Social media links
  social: {
    twitter: "",
    linkedin: "",
    facebook: "",
    github: "",
  },

  // Business information
  business: {
    founded: 2025,
    type: "LLC",
    industry: "technology",
    employees: "1-10",
  },

  // Features/capabilities
  features: {
    highlight:
      "Our unique value proposition that sets us apart from the competition",
    list: [
      {
        icon: "⚡",
        title: "Lightning Fast",
        description: "Blazing fast performance with 99.9% uptime.",
      },
      {
        icon: "🔒",
        title: "Secure & Reliable",
        description: "Enterprise-grade security you can trust.",
      },
      {
        icon: "📊",
        title: "Analytics Dashboard",
        description: "Comprehensive insights into your data.",
      },
      {
        icon: "🔄",
        title: "Auto Sync",
        description: "Seamless synchronization across all devices.",
      },
      {
        icon: "🎯",
        title: "Smart Automation",
        description: "AI-powered workflows that save time.",
      },
      {
        icon: "📱",
        title: "Mobile Ready",
        description: "Perfect experience on any device.",
      },
    ],
  },

  // Statistics (customize with your actual data)
  stats: [
    { value: "1K+", label: "Happy Customers" },
    { value: "99.9%", label: "Uptime" },
    { value: "24/7", label: "Support" },
    { value: "5★", label: "Average Rating" },
  ],

  // Process steps
  process: [
    {
      number: "1",
      title: "Get Started",
      description: "Sign up and complete our quick setup process.",
    },
    {
      number: "2",
      title: "Customize",
      description: "Configure everything to match your needs perfectly.",
    },
    {
      number: "3",
      title: "Launch",
      description: "Go live and start seeing results immediately.",
    },
  ],

  // Call-to-action buttons
  cta: {
    primary: {
      text: "Get Started Free",
      href: "#contact",
    },
    secondary: {
      text: "Learn More",
      href: "#features",
    },
  },

  // Navigation menu items
  navigation: [
    { text: "Features", href: "#features" },
    { text: "How It Works", href: "#how-it-works" },
    { text: "FAQ", href: "#faq" },
    { text: "Contact", href: "#contact" },
  ],

  // SEO and meta tags
  seo: {
    keywords: ["software"],
    ogImage: "/og-image.jpg",
    twitterCard: "summary_large_image",
  },

  // Legal pages
  legal: {
    companyName: "Fake Company, LLC",
    lastUpdated: "2025-09-13",
  },

  // Theme configuration
  theme: {
    primaryColor: "#ef4444",
    secondaryColor: "#3b82f6",
    darkMode: false,
    fonts: {
      heading: "Inter, sans-serif",
      body: "Inter, sans-serif",
    },
  },
} as const;

// Content for different sections
export const CONTENT = {
  hero: {
    title: "",
    subtitle: "Next.js Website Template",
    description: "This is a demonstration website.",
  },

  about: {
    title: "About Fake Company",
    description:
      "We're passionate about delivering exceptional results through innovative solutions and outstanding service.",
  },
};

export type SiteConfig = typeof SITE_CONFIG;
export type SiteContent = typeof CONTENT;
